name: Triple coinflips
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  flip1:
    name: Flip A
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deterministic-coinflip
        with:
          salt: alpha
          sha: ${{ github.event.pull_request.head.sha }}

  flip2:
    name: Flip B
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deterministic-coinflip
        with:
          salt: bravo
          sha: ${{ github.event.pull_request.head.sha }}

  flip3:
    name: Flip C
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deterministic-coinflip
        with:
          salt: charlie
          sha: ${{ github.event.pull_request.head.sha }}

  flip4:
    name: Flip D
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/deterministic-coinflip
        with:
          salt: delta
          sha: ${{ github.event.pull_request.head.sha }}
